// Dark humor & developer existential dread
export const darkQuotes = [
  { text: "My code doesn't have bugs. It has random surprise features. Like a haunted house.", vibe: "dark" },
  { text: "I've reached the age where my back goes out more than I do.", vibe: "dark" },
  { text: "If debugging is the process of removing bugs, then programming must be the process of putting them in. — Dijkstra, probably while crying.", vibe: "dark" },
  { text: "My code is like my life: full of errors, poorly documented, and I'm too tired to fix it.", vibe: "dark" },
  { text: "I don't need therapy. I just need my tests to pass. (I probably need therapy too.)", vibe: "dark" },
  { text: "Every time you write 'TODO: fix later,' a senior developer loses their wings.", vibe: "dark" },
  { text: "The code worked once. That was its one time.", vibe: "dark" },
  { text: "I didn't fail. I just found 10,000 ways that won't compile.", vibe: "sarcastic" },
  { text: "My code is self-documenting. Unfortunately, it's a tragedy.", vibe: "dark" },
  { text: "I'm not saying my code is bad, but the linter started crying.", vibe: "sarcastic" },
  { text: "Writing code without tests is like driving a car with your eyes closed. Eventually, you'll hit something. Probably production.", vibe: "dark" },
  { text: "The project is due tomorrow. Naturally, I'm starting now. This is fine.", vibe: "dark" },
  { text: "I have a joke about UDP but I'm not sure you'll get it.", vibe: "nerdy" },
  { text: "A SQL query walks into a bar, sees two tables, and asks: 'Can I JOIN you?' They divorce 3 years later due to irreconcilable foreign key constraints.", vibe: "dark" },
  { text: "I'd tell you a UDP joke, but you might not get it. I'd tell you a TCP joke, but I'd have to keep telling it until you got it.", vibe: "nerdy" },
  { text: "There are only 10 types of people: those who understand binary and those who don't.", vibe: "nerdy" },
  { text: "A programmer's wife tells him: 'Go to the store and buy a loaf of bread. If they have eggs, buy a dozen.' He comes home with 12 loaves of bread.", vibe: "nerdy" },
  { text: "My code is like my ex: lots of broken promises and I can't figure out what went wrong.", vibe: "dark" },
  { text: "I've been programming so long that 'cloud' used to mean something in the sky.", vibe: "dark" },
  { text: "The senior developer who asked me to fix this 'small bug' has been promoted to CTO and left. I am alone. The bug remains.", vibe: "dark" },
  { text: "I'm not lazy. I'm on energy-saving mode. Like my laptop after 47 tabs of documentation.", vibe: "sarcastic" },
  { text: "Every line of code I write increases the entropy of the universe. I'm basically a heat death accelerator.", vibe: "dark" },
  { text: "My code has more edge cases than a geometry textbook.", vibe: "sarcastic" },
  { text: "I once spent 6 hours debugging a production issue. The issue was me. On the staging server. For 5 hours and 59 minutes.", vibe: "dark" },
  { text: "They say 'practice makes perfect.' I've been practicing for years. The code is not perfect.", vibe: "dark" },
  { text: "I don't always write bugs, but when I do, they're in production at 4:59pm on a Friday.", vibe: "dark" },
  { text: "The code compiles. I know not how. I know not why. But I shall not touch it again.", vibe: "dark" },
  { text: "My imposter syndrome and I have agreed to coexist. Until the next code review. Then we both panic.", vibe: "dark" },
  { text: "I've accepted that my code will never be perfect. But it WILL be someone else's problem. — Legacy code philosophy.", vibe: "dark" },
  { text: "Every successful codebase is the result of a developer googling the error message at 2am.", vibe: "dark" },
  { text: "I'm not afraid of death. I'm afraid of being the person who broke prod at 3am and the pager goes off.", vibe: "dark" },
  { text: "My commit history is a cry for help written in semicolons.", vibe: "dark" },
];
