// Meme quotes by mood
export const memeQuotes = [
  // 😂 Classic Memes
  { text: "This is fine. 🔥🐕", vibe: "chaotic" },
  { text: "Nobody: ... Me at 3am: what if we rewrite everything in Rust?", vibe: "chaotic" },
  { text: "It ain't much, but it's honest work. — After fixing one typo in a 4000-line file.", vibe: "sarcastic" },
  { text: "Stonks. — After adding console.log('here') to production.", vibe: "chaotic" },
  { text: "They don't know I've been copy-pasting from Stack Overflow since 2014.", vibe: "sarcastic" },
  { text: "Surprised Pikachu face when the unchecked promise rejects.", vibe: "sarcastic" },
  { text: "Press F to pay respects to the legacy codebase.", vibe: "dark" },
  { text: "Am I a joke to you? — The junior dev reading the senior's 'clever' one-liner.", vibe: "dark" },
  { text: "One does not simply deploy to production on a Friday.", vibe: "sarcastic" },
  { text: "I'll just quickly fix this bug. *6 hours later* ...what have I done?", vibe: "chaotic" },
  { text: "Plot twist: the bug was a feature all along. And the feature is now a CVE.", vibe: "dark" },
  { text: "Task failed successfully.", vibe: "chaotic" },
  { text: "Change my mind: semicolons are optional and I am a professional.", vibe: "sarcastic" },
  { text: "Me: I'll just write one more function. Also me: 247 commits later.", vibe: "chaotic" },
  { text: "How do you know I code? I'll tell you. I have dark circles under my eyes and a folder called 'experiments' with 14 broken projects.", vibe: "dark" },
  { text: "I don't always test my code, but when I do, I do it in production.", vibe: "chaotic" },
  { text: "Confused Nicholas looking at the TypeScript error that makes absolutely no sense.", vibe: "sarcastic" },
  { text: "Distracted boyfriend: Me looking at a new JavaScript framework while React cries in the background.", vibe: "sarcastic" },
  { text: "Expanding brain: var → let → const → const with a prayer.", vibe: "sarcastic" },
  { text: "Drake no: reading documentation. Drake yes: reading the top Stack Overflow answer from 2013.", vibe: "sarcastic" },
  { text: "Always has been. 🌍🔫 — 'Wait, the tests actually pass?'", vibe: "chaotic" },
  { text: "The bug: exists. Me: adds try-catch. The bug: still exists. Me: adds another try-catch.", vibe: "chaotic" },
  { text: "POV: You just discovered the codebase uses eval().", vibe: "dark" },
  { text: "Tell me you don't have code review without telling me you don't have code review.", vibe: "sarcastic" },
  { text: "Skill issue. — To every bug I encounter.", vibe: "chaotic" },
  { text: "L + ratio + your CI is failing + cope. — My GitHub Actions workflow.", vibe: "chaotic" },
  { text: "Bro really thought the regex would work on the first try. 💀", vibe: "sarcastic" },
  { text: "Not me spending 4 hours debugging only to find out I was on the wrong branch.", vibe: "dark" },
  { text: "Touch grass. — The linter after I've been coding for 14 hours straight.", vibe: "dark" },
  { text: "I fear the day AI takes over. But until then, I fear merge conflicts more.", vibe: "dark" },

  // 🎮 Gaming Memes
  { text: "Git gud. — To every bug.", vibe: "chaotic" },
  { text: "GG EZ. — After the tests finally pass.", vibe: "chaotic" },
  { text: "Skill issue detected. Initiating stack overflow protocol.", vibe: "chaotic" },
  { text: "I didn't choose the debugging life. The debugging life chose me.", vibe: "dark" },
  { text: "Speedrun any%: write code, deploy, cry, fix, repeat. World record: 4 hours.", vibe: "chaotic" },
  { text: "New personal best: 73 tabs open while debugging. Previous record: 72.", vibe: "sarcastic" },
  { text: "Achievement unlocked: made it work without understanding why.", vibe: "sarcastic" },
  { text: "Loading... please wait... still loading... maybe refresh?", vibe: "chaotic" },
];
