// Movie & TV quotes organized by vibe
export const movieQuotes = [
  // 😈 Dark / Sarcastic / Menacing
  { text: "I'm gonna make him an offer he can't refuse.", vibe: "menacing" },
  { text: "You can't handle the truth!", vibe: "dramatic" },
  { text: "I am the one who knocks.", vibe: "menacing" },
  { text: "Say hello to my little friend!", vibe: "chaotic" },
  { text: "I have always depended on the kindness of strangers. And the kindness of well-documented APIs.", vibe: "sarcastic" },
  { text: "Nobody puts Baby in a corner. Except maybe a CSS flexbox.", vibe: "nerdy" },
  { text: "Here's Johnny! And he brought a debugger.", vibe: "chaotic" },
  { text: "I see dead code.", vibe: "dark" },
  { text: "It's alive! IT'S ALIVE! ...wait, the tests pass?", vibe: "chaotic" },
  { text: "Go ahead, make my day. Deploy to production on a Friday.", vibe: "dark" },
  { text: "I'll be back. After this merge conflict.", vibe: "menacing" },
  { text: "May the Force be with you. And by Force, I mean Stack Overflow.", vibe: "nerdy" },
  { text: "There is no spoon. There is only undefined.", vibe: "nerdy" },
  { text: "You talking to me? You talking to ME? Well I'm the only one here... thanks to git blame.", vibe: "sarcastic" },
  { text: "I feel the need... the need for speed. And by speed I mean a passing CI pipeline.", vibe: "nerdy" },
  { text: "Life is like a box of chocolates. You never know which dependency will break semver.", vibe: "sarcastic" },
  { text: "Houston, we have a problem. The problem is line 42.", vibe: "dramatic" },
  { text: "To infinity and beyond! (Of the call stack.)", vibe: "chaotic" },
  { text: "After all, tomorrow is another day. Another sprint, another standup.", vibe: "dark" },
  { text: "Elementary, my dear Watson. The bug was a missing semicolon.", vibe: "nerdy" },
  { text: "You either die a hero or live long enough to see yourself become the villain. Or in tech: you either ship on time or become tech debt.", vibe: "dark" },
  { text: "Frankly, my dear, I don't give a damn. — Every developer after the 14th code review iteration.", vibe: "sarcastic" },
  { text: "I'm the king of the world! ...until the senior architect reviews my PR.", vibe: "sarcastic" },
  { text: "Why so serious? It's just a segmentation fault.", vibe: "chaotic" },
  { text: "With great power comes great responsibility. And with great seniority comes great blame in git.", vibe: "dark" },
  { text: "I'm walking here! I'm walking here! ...through 47 directories of node_modules.", vibe: "sarcastic" },
  { text: "E.T. phone home. (It's calling the API endpoint.)", vibe: "nerdy" },
  { text: "Keep your friends close, but your enemies closer. Keep your dependencies closest.", vibe: "sarcastic" },
  { text: "Just when I thought I was out, they pull me back in. — Every dev returning from vacation to legacy code.", vibe: "dark" },
  { text: "The first rule of Fight Club is: you do not talk about Fight Club. The first rule of this codebase is: you do not touch utils/helpers.", vibe: "dark" },

  // 🎬 Action / Epic
  { text: "Yippee-ki-yay, motherf***er.", vibe: "chaotic" },
  { text: "I'm too old for this s***.", vibe: "dark" },
  { text: "Get to the chopper! Get to the CHOPPER! Get to the CI pipeline!", vibe: "chaotic" },
  { text: "Consider that a divorce. — Between the frontend and the backend.", vibe: "sarcastic" },
  { text: "I'm not a smart man, but I know what null means.", vibe: "sarcastic" },
  { text: "Roads? Where we're going, we don't need roads. We have TypeScript.", vibe: "nerdy" },
  { text: "It's not a tumor. It's a null pointer exception.", vibe: "sarcastic" },
  { text: "I drink your milkshake! I DRINK YOUR MIGRATION!", vibe: "chaotic" },
  { text: "The cake is a lie. The documentation is a lie.", vibe: "dark" },
  { text: "This is Sparta! This is PRODUCTION!", vibe: "chaotic" },
  { text: "I am Groot. (Translation: the regex is too greedy.)", vibe: "nerdy" },
  { text: "A martini. Shaken, not stirred. Like my confidence after a 'quick fix.'", vibe: "sarcastic" },
  { text: "I am inevitable. — Technical debt, probably.", vibe: "dark" },
  { text: "Wakanda forever! ...and may our uptime be eternal.", vibe: "nerdy" },
  { text: "I am Iron Man. And this is my 47th cup of coffee.", vibe: "chaotic" },
  { text: "Name. Bond. James Bond. — My commit message after 3am.", vibe: "sarcastic" },
];
