// Rocky from Project Hail Mary — movie + book quotes, adapted for coding
export const rockyQuotes = [
  { text: "Good, good.", vibe: "rocky" },
  { text: "Amaze, amaze, amaze.", vibe: "rocky" },
  { text: "Grace Rocky save stars.", vibe: "rocky" },
  { text: "Grace question is dumb.", vibe: "rocky" },
  { text: "Oh, humor. Confusing.", vibe: "rocky" },
  { text: "Rocky, Grace, big science.", vibe: "rocky" },
  { text: "Fist my bump.", vibe: "rocky" },
  { text: "Only us.", vibe: "rocky" },
  { text: "Dirty, dirty, dirty... This room for garbage?", vibe: "rocky" },
  { text: "It's not enough.", vibe: "rocky" },
  { text: "Rocky watch crew die, could not fix. Grace say Grace will die, Rocky fix.", vibe: "rocky" },
  { text: "Need word: to risk self to help another.", vibe: "rocky" },
  { text: "How do you know when the hug is done?", vibe: "rocky" },
  { text: "Rocky hate Mark.", vibe: "rocky" },
  { text: "Thumbs up, baby.", vibe: "rocky" },
  { text: "My portable Earth thinking machine.", vibe: "rocky" },
  { text: "Rocky hate buggy code.", vibe: "rocky" },
  { text: "Need word: to stare at compiler errors for hours until they go away from fear.", vibe: "rocky" },
  { text: "Good, good. This function... amaze.", vibe: "rocky" },
  { text: "Grace question is dumb. Read documentation first.", vibe: "rocky" },
  { text: "Rocky watch production crash, could not fix. You say production will crash, Rocky fix.", vibe: "rocky" },
  { text: "Dirty, dirty, dirty... This codebase for garbage?", vibe: "rocky" },
  { text: "Rocky, you, big science. We refactor this together.", vibe: "rocky" },
  { text: "Oh, humor. Confusing. Why is null a feature?", vibe: "rocky" },
  { text: "It's not enough. The test coverage is not enough.", vibe: "rocky" },
  { text: "Amaze, amaze, amaze. The CI pipeline is green.", vibe: "rocky" },
  { text: "Need word: to deploy on Friday and hope for the best.", vibe: "rocky" },
  { text: "Good, good. Your code is... amaze.", vibe: "rocky" },
  { text: "Rocky hate merge conflict.", vibe: "rocky" },
  { text: "Only us. You and me and this bug at 3am.", vibe: "rocky" },
];
