keymap:
  - name: Kitty
    application:
      only: kitty
    remap:
      Alt_L-n: C-Shift-n
      Alt_L-c: C-Shift-c
      Alt_L-v: C-Shift-v
  - name: Tilix
    application:
      only: Tilix
    remap:
      Alt_L-n: C-Shift-n
      Alt_L-c: C-Shift-c
      Alt_L-v: C-Shift-v
  - name: Firefox
    application:
      only: firefox
    remap:
      Alt_L-w: C-w
      Alt_L-f: C-f
      Alt_L-r: C-r
  - name: Standard bindings
    remap:
      C-a: left
      C-d: right
      C-w: up
      C-s: down
      Alt_L-c: C-c
      Alt_L-v: C-v
      Alt_L-t: C-t
      Ctrl-z: KEY_102ND
      Ctrl-Shift-z: Shift-KEY_102ND
      Ctrl-Shift-KEY_BACKSLASH: Shift-KEY_GRAVE
      Ctrl-KEY_BACKSLASH: KEY_GRAVE
